version: '3.5'

services:      
  botpress:
    image: botpress/server:v12_25_0
    volumes:
      - botpress-data:/botpress/data
    environment:
      - BP_CONFIG_HTTPSERVER_HOST=0.0.0.0
      - BP_MODULE_NLU_DUCKLINGURL=https://duckling.botpress.io/
      - EXTERNAL_URL=http://127.0.0.1:3000/
    ports:
       - 3001:3000
    networks:
      - web
      - rocketchat
    healthcheck:
      disable: true

volumes:
  botpress-data:
    driver: local
      
networks:
  web:
    external: 
      name: web
  rocketchat:
    external:
      name: rocketchat_default